"""add_ward_reports_table

Revision ID: 15e3d7001245
Revises: 3d08d22e4292
Create Date: 2026-06-28 17:01:28.366805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '15e3d7001245'
down_revision: Union[str, None] = '3d08d22e4292'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ward_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ward', sa.String(length=128), nullable=False),
    sa.Column('week_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('week_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('narrative', sa.Text(), nullable=False),
    sa.Column('headline', sa.String(length=256), nullable=False),
    sa.Column('key_achievements', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('key_concerns', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('agent_model', sa.String(length=64), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ward_reports_ward', 'ward_reports', ['ward'], unique=False)
    op.create_index('ix_ward_reports_week_start', 'ward_reports', ['week_start'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ward_reports_week_start', table_name='ward_reports')
    op.drop_index('ix_ward_reports_ward', table_name='ward_reports')
    op.drop_table('ward_reports')
    # ### end Alembic commands ###
