"""add_escalation_fields_to_issues

Revision ID: 3d08d22e4292
Revises: 0004
Create Date: 2026-06-28 16:18:27.007837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d08d22e4292'
down_revision: Union[str, None] = '0004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('issues', sa.Column('escalation_count', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_triage_reports_issue_id'), table_name='triage_reports')
    op.create_index('ix_triage_reports_issue_id', 'triage_reports', ['issue_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_triage_reports_issue_id', table_name='triage_reports')
    op.create_index(op.f('ix_triage_reports_issue_id'), 'triage_reports', ['issue_id'], unique=True)
    op.drop_column('issues', 'escalation_count')
    op.drop_column('issues', 'escalated_at')
    # ### end Alembic commands ###
