"""add_ondelete_set_null_to_user_fks

Revision ID: 9ebb54b15bfa
Revises: 15e3d7001245
Create Date: 2026-06-29 16:29:30.061877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ebb54b15bfa'
down_revision: Union[str, None] = '15e3d7001245'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assignments', 'assigned_to',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('assignments', 'assigned_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('assignments_assigned_to_fkey'), 'assignments', type_='foreignkey')
    op.drop_constraint(op.f('assignments_assigned_by_fkey'), 'assignments', type_='foreignkey')
    op.create_foreign_key(None, 'assignments', 'users', ['assigned_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'assignments', 'users', ['assigned_to'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('comments_user_id_fkey'), 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('flags', 'flagged_by',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('flags_reviewed_by_fkey'), 'flags', type_='foreignkey')
    op.drop_constraint(op.f('flags_flagged_by_fkey'), 'flags', type_='foreignkey')
    op.create_foreign_key(None, 'flags', 'users', ['reviewed_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'flags', 'users', ['flagged_by'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('issue_audit_log_actor_id_fkey'), 'issue_audit_log', type_='foreignkey')
    op.create_foreign_key(None, 'issue_audit_log', 'users', ['actor_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('issues_assigned_to_fkey'), 'issues', type_='foreignkey')
    op.drop_constraint(op.f('issues_reporter_id_fkey'), 'issues', type_='foreignkey')
    op.create_foreign_key(None, 'issues', 'users', ['assigned_to'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'issues', 'users', ['reporter_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('leaderboard_points_user_id_fkey'), 'leaderboard_points', type_='foreignkey')
    op.create_foreign_key(None, 'leaderboard_points', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('resolution_feedback_submitted_by_fkey'), 'resolution_feedback', type_='foreignkey')
    op.create_foreign_key(None, 'resolution_feedback', 'users', ['submitted_by'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('status_history_changed_by_fkey'), 'status_history', type_='foreignkey')
    op.create_foreign_key(None, 'status_history', 'users', ['changed_by'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('user_badges_user_id_fkey'), 'user_badges', type_='foreignkey')
    op.create_foreign_key(None, 'user_badges', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('verifications', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint(op.f('uq_verification_issue_user'), 'verifications', type_='unique')
    op.create_index('ix_verif_issue_user_unique', 'verifications', ['issue_id', 'user_id'], unique=True, postgresql_where=sa.text('user_id IS NOT NULL'))
    op.drop_constraint(op.f('verifications_user_id_fkey'), 'verifications', type_='foreignkey')
    op.create_foreign_key(None, 'verifications', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('votes_user_id_fkey'), 'votes', type_='foreignkey')
    op.create_foreign_key(None, 'votes', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'votes', type_='foreignkey')
    op.create_foreign_key(op.f('votes_user_id_fkey'), 'votes', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'verifications', type_='foreignkey')
    op.create_foreign_key(op.f('verifications_user_id_fkey'), 'verifications', 'users', ['user_id'], ['id'])
    op.drop_index('ix_verif_issue_user_unique', table_name='verifications', postgresql_where=sa.text('user_id IS NOT NULL'))
    op.create_unique_constraint(op.f('uq_verification_issue_user'), 'verifications', ['issue_id', 'user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('verifications', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'user_badges', type_='foreignkey')
    op.create_foreign_key(op.f('user_badges_user_id_fkey'), 'user_badges', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'status_history', type_='foreignkey')
    op.create_foreign_key(op.f('status_history_changed_by_fkey'), 'status_history', 'users', ['changed_by'], ['id'])
    op.drop_constraint(None, 'resolution_feedback', type_='foreignkey')
    op.create_foreign_key(op.f('resolution_feedback_submitted_by_fkey'), 'resolution_feedback', 'users', ['submitted_by'], ['id'])
    op.drop_constraint(None, 'leaderboard_points', type_='foreignkey')
    op.create_foreign_key(op.f('leaderboard_points_user_id_fkey'), 'leaderboard_points', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'issues', type_='foreignkey')
    op.drop_constraint(None, 'issues', type_='foreignkey')
    op.create_foreign_key(op.f('issues_reporter_id_fkey'), 'issues', 'users', ['reporter_id'], ['id'])
    op.create_foreign_key(op.f('issues_assigned_to_fkey'), 'issues', 'users', ['assigned_to'], ['id'])
    op.drop_constraint(None, 'issue_audit_log', type_='foreignkey')
    op.create_foreign_key(op.f('issue_audit_log_actor_id_fkey'), 'issue_audit_log', 'users', ['actor_id'], ['id'])
    op.drop_constraint(None, 'flags', type_='foreignkey')
    op.drop_constraint(None, 'flags', type_='foreignkey')
    op.create_foreign_key(op.f('flags_flagged_by_fkey'), 'flags', 'users', ['flagged_by'], ['id'])
    op.create_foreign_key(op.f('flags_reviewed_by_fkey'), 'flags', 'users', ['reviewed_by'], ['id'])
    op.alter_column('flags', 'flagged_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key(op.f('comments_user_id_fkey'), 'comments', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.drop_constraint(None, 'assignments', type_='foreignkey')
    op.create_foreign_key(op.f('assignments_assigned_by_fkey'), 'assignments', 'users', ['assigned_by'], ['id'])
    op.create_foreign_key(op.f('assignments_assigned_to_fkey'), 'assignments', 'users', ['assigned_to'], ['id'])
    op.alter_column('assignments', 'assigned_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('assignments', 'assigned_to',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
