"""add_ward_reports_generated_at_index

Revision ID: b785dbfa9cb8
Revises: e4805ca63f69
Create Date: 2026-06-30 08:08:52.394304

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b785dbfa9cb8'
down_revision: Union[str, None] = 'e4805ca63f69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_ward_reports_generated_at', 'ward_reports', ['generated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ward_reports_generated_at', table_name='ward_reports')
    # ### end Alembic commands ###
