"""add_offlinedraft_user_id_ondelete

Revision ID: e4805ca63f69
Revises: 9ebb54b15bfa
Create Date: 2026-06-29 18:30:08.828785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4805ca63f69'
down_revision: Union[str, None] = '9ebb54b15bfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('offline_drafts_user_id_fkey'), 'offline_drafts', type_='foreignkey')
    op.create_foreign_key(None, 'offline_drafts', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'offline_drafts', type_='foreignkey')
    op.create_foreign_key(op.f('offline_drafts_user_id_fkey'), 'offline_drafts', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
